# docker-publish.sh prepends header with LABELs
# FROM python:3.14-slim
# the correct usage is {echo "<HEADER>"; cat Dockerfile.base} | docker build ...

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install poetry \
 && poetry config virtualenvs.create false \
 && poetry install --without dev --no-interaction --no-ansi

COPY bot ./bot

CMD ["python", "-m", "bot.main"]
